### ISSUE TITLE
9Gem HD not working

### ISSUE THREAD

**Issue by willat8** [ShephedProject/shepherd#28]
I've noticed about 10 days ago there's no more guide data for 9Gem HD- anyone else experiencing the same?

**Comment by Flic182** [comment]
Yes.  You can get it working with the following instructions, but please - **back up the original files first** in case something goes wrong and you need to restore them.

The name has changed from `9Gem HD` to `9GemHD` (i.e. lose the space before `HD`).  If you update the `channels.conf` and `references/channel_list/channel_list` files (under `~/.shepherd`) to use the new name, it should work.  Do note, this will make shepherd complain the `channels.conf` file is tainted because the checksum no longer matches and you will have to wait for a 10 second countdown before shepherd will run with your modifications.  It should be OK after that though.  There is a good discussion of this under issue [#27 ](https://github.com/ShephedProject/shepherd/issues/27).

This is related to the 10 Shake issue - [#26 ](https://github.com/ShephedProject/shepherd/issues/26).  In that case, update the `10 Shake` references to `10 SHAKE`.

**Comment by willat8** [comment]
Thank you for this.

**Comment by willat8** [comment]
This didn't seem to work for 9GemHD, at least for the rex grabber (it did work fine for 10 SHAKE though).

Looks like rex scrapes yourtv.com.au, and 9GemHD has been dropped there.

**Comment by thiakil** [comment]
@willat8 what region?

**Comment by willat8** [comment]
Sydney metropolitan - 73

**Comment by thiakil** [comment]
9GemHD is listed in their channel list, but the guide data doesn't contain anything specific for the hd channel. Appears to be the same for other sources too.
Do any of the programs on the SD one get marked as being in HD?

**Comment by willat8** [comment]
I checked with

```
grep -A10 HDTV output.xmltv | grep -i gem
```

and got no matches.
